---
rbac:
  install: true

Master:
  Image:    jenkins/jenkins
  ImageTag: "2.150"
  ServiceType: ClusterIP
  HostName:    jenkins.192.168.99.100.nip.io

  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx

Persistence:
  Enabled: true
  StorageClass: standard
  Size: 2Gi